/*
  # Add Complete Menu Data

  ## Overview
  This migration populates the complete menu data from the PDF menu file.
*/

DELETE FROM category_items;
DELETE FROM categories;

INSERT INTO categories (name_en, name_ar, icon_type, item_count, sort_order) VALUES
('Hookah', 'معسل تفاحتين', 'pantry', 3, 1),
('Manakish', 'مناقيش', 'bread', 7, 2),
('Chicken Meals', 'وجبات دجاج', 'chicken', 13, 3),
('Meat Meals', 'وجبات اللحمة', 'meat', 6, 4),
('Kids Meals', 'وجبات اطفال', 'fire', 3, 5),
('Seafood Meals', 'وجبات بحرية', 'soup', 4, 6),
('Diet Meals', 'وجبات دايت', 'salad', 6, 7),
('Sandwiches', 'السندويش', 'sandwich', 6, 8),
('Soups', 'الشوربات', 'soup', 6, 9),
('Cold Salads', 'السلطات', 'salad', 10, 10),
('Hot Appetizers', 'المقبالت الساخنة', 'appetizer', 16, 11),
('Pasta', 'الباستا', 'fire', 5, 12),
('Breakfast', 'الفطور', 'bread', 13, 13),
('Set Meals', 'سيت', 'fire', 11, 14),
('Extra Kitchen', 'مطبخ اكسترا', 'fire', 48, 15),
('Hot Drinks', 'المشروبات الساخنة', 'fire', 48, 16),
('Sports Drink', 'سبورت درينك', 'fire', 9, 17),
('Ice Tea', 'ايس تي', 'fire', 5, 18),
('Smoothies', 'صودا', 'fire', 25, 19),
('Seasonal Juices', 'العصائر الموسمية', 'fire', 15, 20),
('Sweet Treats', 'الحلويات', 'fire', 7, 21);

INSERT INTO category_items (category_id, name_en, name_ar, price) VALUES
((SELECT id FROM categories WHERE name_ar = 'معسل تفاحتين'), 'Arkileh Mussel', 'اركٌلة معسل', 35000),
((SELECT id FROM categories WHERE name_ar = 'معسل تفاحتين'), 'Tadbeel Mussel', 'تبدٌل معسل', 20000),
((SELECT id FROM categories WHERE name_ar = 'معسل تفاحتين'), 'Barbish Sihi', 'بربٌش صحً', 7000),
((SELECT id FROM categories WHERE name_ar = 'مناقيش'), 'Manakish with White Cheese and Vegetables', 'منقوشة جبنة بٌضا مع خضار', 38000),
((SELECT id FROM categories WHERE name_ar = 'مناقيش'), 'Manakish with Roasted Red Pepper', 'منقوشة محمرة مع قشقوان', 38000),
((SELECT id FROM categories WHERE name_ar = 'مناقيش'), 'Manakish with Labneh and Makdous', 'منقوشة لبنة ومكدوس', 41000),
((SELECT id FROM categories WHERE name_ar = 'مناقيش'), 'Manakish with Zaatar and Vegetables', 'منقوشة زعتر مع خضار', 25000),
((SELECT id FROM categories WHERE name_ar = 'مناقيش'), 'Manakish with Labneh and Sumac', 'منقوشة لبنة مع سماق', 27000),
((SELECT id FROM categories WHERE name_ar = 'مناقيش'), 'Shawarma Chicken', 'شاورما دجاج', 78000),
((SELECT id FROM categories WHERE name_ar = 'مناقيش'), 'Shawarma Meat', 'شاورما لحمة', 107000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Fakharah Tornado', 'فخارة تورنادو', 162000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Tawook Chicken', 'ترٌاكً تشكن', 135000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Grilled Chicken Lemon Herbs', 'دجاج مشوي لٌمون واعشاب', 137000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Chicken Marsala', 'تشكن مارساال', 140000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Chicken Cordon', 'تشكن كوردون', 140000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Chicken Napoli', 'تشكن نابولً', 152000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Creamy Chicken Mozzarella', 'كرٌمً تشكن موزرٌال وبرمٌزان', 146000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Spanish Chicken Roll', 'اسبانٌش تشكن رول', 137000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Fusion Chicken Cashew', 'فٌوجن تشكن كاجو', 145000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Chicken Yogurt Sauce', 'دجاج مع صلصة زبادي واعشاب', 128000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Chicken Pop Corn', 'تشكن بوب كورن', 126000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Crispy Cheddar Sauce', 'كرٌسبً صلصة شٌدر', 119000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دجاج'), 'Chicken Tahini Skewer', 'شٌش طاووق مع سلطة الرز', 119000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اللحمة'), 'Beef Stroganoff', 'بٌؾ استراؼنوؾ', 198000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اللحمة'), 'Saffron Steak', 'ستٌك زعفران', 223000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اللحمة'), 'Entrecote Steak', 'انتركوت ستٌك', 214000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اللحمة'), 'Filet Rockefort', 'فٌلٌه ركفورد', 210000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اللحمة'), 'Filet Mustard', 'فٌلٌه ماسترد', 206000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اللحمة'), 'Filet Mushroom', 'فٌلٌه مشروم', 204000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اطفال'), 'Chicken Pop Corn', 'تشكن بوب كورن', 126000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اطفال'), 'Crispy Cheddar', 'كرٌسبً صلصة شٌدر', 119000),
((SELECT id FROM categories WHERE name_ar = 'وجبات اطفال'), 'Fish and Chips', 'فٌش آند شٌبس', 138000),
((SELECT id FROM categories WHERE name_ar = 'وجبات بحرية'), 'Grilled Hamour Cream', 'هامور مشوي كرٌم لٌمون واعشاب', 142000),
((SELECT id FROM categories WHERE name_ar = 'وجبات بحرية'), 'Shrimp Kong Pao', 'شرمب كونػ باو', 225000),
((SELECT id FROM categories WHERE name_ar = 'وجبات بحرية'), 'Fish Chips', 'فٌش آند شٌبس', 138000),
((SELECT id FROM categories WHERE name_ar = 'وجبات بحرية'), 'Seafood Mix', 'مزيج أسماك', 150000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دايت'), 'Fish Filet Herbs Quinoa', 'فٌلٌه سمك مع اعشاب وكٌنوا', 136000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دايت'), 'Steak Arugula Balsamic', 'ستٌك مع جرجٌر وبلسمٌك و رز الصوٌا', 193000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دايت'), 'Crispy Sweet Potato', 'كرٌسبً مع بطاطا حلوة محمصة', 107000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دايت'), 'Scallop Halloumi', 'اسكالوب حلومً مع بطاطا حلوة محمصة', 110000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دايت'), 'Fajita Raps Chicken', 'فاهٌتا رابس تشكن', 114000),
((SELECT id FROM categories WHERE name_ar = 'وجبات دايت'), 'Tuna Sandwich', 'تونا ساندوٌش', 99000),
((SELECT id FROM categories WHERE name_ar = 'السندويش'), 'Mushroom Burger BBQ', 'مشروم برؼر باربكٌو', 128000),
((SELECT id FROM categories WHERE name_ar = 'السندويش'), 'Classic Cheddar Burger', 'كالسٌك تشٌدر برؼر', 120000),
((SELECT id FROM categories WHERE name_ar = 'السندويش'), 'Crispy Chicken Sandwich', 'كرٌسبً تشكن ساندوٌش', 103000),
((SELECT id FROM categories WHERE name_ar = 'السندويش'), 'Philadelphia Steak', 'فٌالدلفٌا ستٌك ساندوٌش', 134000),
((SELECT id FROM categories WHERE name_ar = 'السندويش'), 'Tuna Sandwich', 'تونا ساندوٌش', 99000),
((SELECT id FROM categories WHERE name_ar = 'السندويش'), 'Chicken Shawarma', 'شاورما دجاج', 78000),
((SELECT id FROM categories WHERE name_ar = 'الشوربات'), 'Lentil with Chicken', 'عدس مع دجاج', 33000),
((SELECT id FROM categories WHERE name_ar = 'الشوربات'), 'Lentil with Oats', 'عدس مع شوفان', 38000),
((SELECT id FROM categories WHERE name_ar = 'الشوربات'), 'Onion Soup', 'شوربة بصل', 46000),
((SELECT id FROM categories WHERE name_ar = 'الشوربات'), 'Cream Mix', 'كرٌمة مٌكس', 54000),
((SELECT id FROM categories WHERE name_ar = 'الشوربات'), 'Quinoa Tabbouleh', 'تبولة كٌنوا', 79000),
((SELECT id FROM categories WHERE name_ar = 'الشوربات'), 'Italian Panzanella', 'بانزٌال االٌطالٌة', 95000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Caesar Chicken', 'سٌزر دجاج', 92000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Caesar Shrimp', 'سٌزر شرمب', 118000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Nachos', 'ناتشوز', 94000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Burritos Chicken', 'بورٌتوس تشكن', 104000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Potato Fries', 'بطاطا فورتشٌز', 84000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Mozzarella Sticks', 'موزرٌال ستٌكز', 75000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Tornado Salad', 'سلطة تورنادو', 98000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Salad Palmetto', 'سلطة بالمٌتو', 108000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Lettuce Hearts', 'قلوب خس ركفورد', 108000),
((SELECT id FROM categories WHERE name_ar = 'السلطات'), 'Thai Beef Noodles', 'تاي بٌؾ نودلز', 133000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Garlic Bread', 'ؼارلٌك برٌد', 64000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Dynamite Shrimp', 'داٌنمٌت شرمب', 135000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Crispy Barbecue', 'كرٌسبً باربكٌو', 78000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Tempura Hot Dog', 'تٌمبورا هوت دوغ', 89000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Rice Chicken Bruschetta', 'راٌس تشكن بروسكٌتا', 78000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'French Fries', 'بطاطا مقلٌة', 49000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Spaghetti Marinara Shrimp', 'اسباؼٌتً مارٌنارا شرمب', 117000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Chicken Fettuccini', 'تشكن فٌتوتشٌنً االفونجً', 106000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Pine Yogurt', 'بٌنه ٌوؼرت', 86000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Tornado Pasta', 'تورنادو باستا', 102000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Veggie Omelet', 'اوملٌت خضار مع موزرٌال', 53000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Croissant Zaatar', 'كروسان زعتر مع خضار', 41000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Croissant Mix Cheese', 'كروسان مٌكس تشٌز مع خضار', 53000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Scramble Ham Avocado', 'سكرامبل مع الحبش واالفوكادو', 57000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Carbonara Omelet', 'كاربونارا اوملٌت كروسان', 81000),
((SELECT id FROM categories WHERE name_ar = 'المقبالت الساخنة'), 'Grilled Vegetables', 'جرجٌر مع شوندر', 77000),
((SELECT id FROM categories WHERE name_ar = 'الباستا'), 'Spaghetti Marinara', 'اسباؼٌتً مارٌنارا شرمب', 117000),
((SELECT id FROM categories WHERE name_ar = 'الباستا'), 'Fettuccini Alfredo', 'تشكن فٌتوتشٌنً االفونجً', 106000),
((SELECT id FROM categories WHERE name_ar = 'الباستا'), 'Pine Yogurt', 'بٌنه ٌوؼرت', 86000),
((SELECT id FROM categories WHERE name_ar = 'الباستا'), 'Tornado Pasta', 'تورنادو باستا', 102000),
((SELECT id FROM categories WHERE name_ar = 'الباستا'), 'Penne Pasta', 'بينا باستا', 95000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Fried Hot Dog', 'هوت دوغ مقلً', 58000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Calzone', 'كالٌزونً', 114000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Avocado Cheese Toast', 'افوكادو تشٌز توست', 86000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Fried Eggs Bacon', 'بٌض عٌون مع البٌكن', 62000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Labneh', 'صحن لبنة', 17000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Grilled Halloumi', 'جبنة حلوم مشوٌة', 28000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Makdous', 'صحن مكدوس', 28000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Zaatar with Vegetables', 'زعتر مع خضار', 22000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Zucchini Vegetables', 'زٌتون مع خضار', 17000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Fool Plate', 'صحن فول', 40000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Feta Cheese Plate', 'فتة حصص', 66000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Hummus Plate', 'صحن حمص', 21000),
((SELECT id FROM categories WHERE name_ar = 'الفطور'), 'Maryeh Plate', 'صحن مريً', 14000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Mix Set', 'مجموعة مكس', 39000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Omelet Scramble', 'صحن اوملٌت او صحن', 28000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'French Fries', 'بطاطا مقلٌة', 49000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Rice Plate', 'صحن رز', 15000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Sauce Mushroom', 'صلصة مطبخية', 12000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Sauce Teriyaki', 'صلصة تٌريٌاكً', 15000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Sauce Cordon', 'صلصة كوردون', 14000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Sauce Cream', 'صلصة كرٌمة', 12000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Sauce Cajun', 'صلصة كاجو', 15000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Sauce Rockefort', 'صلصة ركفورد', 14000),
((SELECT id FROM categories WHERE name_ar = 'سيت'), 'Extra Cheese', 'اكسترا جبنة بارمٌزان', 16000),
((SELECT id FROM categories WHERE name_ar = 'مطبخ اكسترا'), 'Extra Mozzarella', 'اكسترا جبنة موزرٌال', 7000),
((SELECT id FROM categories WHERE name_ar = 'مطبخ اكسترا'), 'Extra Cheddar', 'اكسترا جبنة تشدر', 11000),
((SELECT id FROM categories WHERE name_ar = 'مطبخ اكسترا'), 'Extra Rockefort', 'اكسترا جبنة ركفورد', 15000),
((SELECT id FROM categories WHERE name_ar = 'مطبخ اكسترا'), 'Extra Mayonnaise', 'اكسترا مايونيز', 6000),
((SELECT id FROM categories WHERE name_ar = 'مطبخ اكسترا'), 'Extra Ketchup', 'اكسترا كتشب', 4000),
((SELECT id FROM categories WHERE name_ar = 'مطبخ اكسترا'), 'Extra Chardonnay', 'اكسترا خردل', 12000),
((SELECT id FROM categories WHERE name_ar = 'المشروبات الساخنة'), 'Tea Lemon', 'شاي مع ليمون', 25000),
((SELECT id FROM categories WHERE name_ar = 'المشروبات الساخنة'), 'Coffee', 'قهوة', 15000),
((SELECT id FROM categories WHERE name_ar = 'المشروبات الساخنة'), 'Tea', 'شاي', 15000),
((SELECT id FROM categories WHERE name_ar = 'المشروبات الساخنة'), 'Mint Tea', 'شاي نعناع', 15000),
((SELECT id FROM categories WHERE name_ar = 'المشروبات الساخنة'), 'Ginger Tea', 'شاي زنجبيل', 15000),
((SELECT id FROM categories WHERE name_ar = 'سبورت درينك'), 'Banana Milk Oat', 'موز وحليب وشوفان', 65000),
((SELECT id FROM categories WHERE name_ar = 'سبورت درينك'), 'Banana Milk Nuts', 'موز وحليب ومكسرات وعسل', 75000),
((SELECT id FROM categories WHERE name_ar = 'سبورت درينك'), 'Avocado', 'افوكادو', 75000),
((SELECT id FROM categories WHERE name_ar = 'سبورت درينك'), 'Hailti Drink', 'هيلتي درينك', 55000),
((SELECT id FROM categories WHERE name_ar = 'سبورت درينك'), 'Sour Drink', 'سور درينك', 60000),
((SELECT id FROM categories WHERE name_ar = 'ايس تي'), 'Iced Tea Lemon', 'آيس تي ليمون', 55000),
((SELECT id FROM categories WHERE name_ar = 'ايس تي'), 'Iced Tea Peach', 'آيس تي دراق', 55000),
((SELECT id FROM categories WHERE name_ar = 'ايس تي'), 'Iced Tea Passion', 'آيس تي باشن فروت', 55000),
((SELECT id FROM categories WHERE name_ar = 'ايس تي'), 'Fresh Iced Tea Ginger', 'فرٌش آٌس تً زنجبٌل ولٌمون', 55000),
((SELECT id FROM categories WHERE name_ar = 'ايس تي'), 'Fresh Iced Tea Orange', 'فرٌش آٌس تً زنجبٌل وبرتقال', 55000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Mojito Classic', 'موهٌتو كالسٌك', 50000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Mojito Peach', 'موهٌتو دراق', 60000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Mojito Passion', 'موهٌتو باشن فروت', 60000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Mojito Mix Berry', 'موهٌتو مٌكس بٌري', 65000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Red and Blue', 'رٌد آند بلو', 60000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Orange Ginger', 'اورنج جنجر مٌري', 60000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Yellow Mix', 'ٌلو مٌكس', 65000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Orange Juice', 'فرٌش جوس برتقال', 40000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Bolo Juice', 'فرٌش جوس بولو', 45000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Freeze Juice', 'فرٌش جوس فرٌز', 45000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Berry Juice', 'فرٌش جوس توت', 45000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Apple Juice', 'فرٌش جوس تفاح', 45000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Carrot Juice', 'فرٌش جوس جزر', 40000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Kiwi Juice', 'فرٌش جوس كٌوي', 50000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Mango Juice', 'فرٌش جوس منؽا', 50000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Pineapple Juice', 'فرٌش جوس اناناس', 50000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Lemon Juice', 'فرٌش جوس ليمون', 40000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Kiwi Pineapple', 'كٌوي واناناس', 50000),
((SELECT id FROM categories WHERE name_ar = 'صودا'), 'Pomegranate', 'عصٌر رمان', 40000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Cheesecake Nutella', 'تشٌز كٌك نوتيلا', 65000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Cheesecake Blueberry', 'تشٌز كٌك بلو بيري', 60000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Cheesecake Lotus', 'تشٌز كٌك لوتس', 65000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Cheesecake Oreo', 'تشٌز كٌك اوريو', 65000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Brownie Tornado', 'براونز تورنادو', 75000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Basmati Two', 'باسمر دو', 50000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Asia Doll', 'اسيا بول دايت', 60000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Caramel Chocolate', 'كاراميل شوكولا', 75000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Pistachio Chocolate', 'بستاشيو شوكولا', 70000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Classic Chocolate', 'كالسيك شوكولا', 70000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Hazel Chocolate', 'هيزل شوكولا', 70000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Frezio Chocolate', 'فريزيو شوكولا', 60000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Freeze Berry', 'فرٌز وتوت', 50000),
((SELECT id FROM categories WHERE name_ar = 'العصائر الموسمية'), 'Freeze Lemon', 'فرٌز ولٌمون', 45000),
((SELECT id FROM categories WHERE name_ar = 'الحلويات'), 'Nutella Cake', 'تشٌز كٌك نوتيلا', 65000),
((SELECT id FROM categories WHERE name_ar = 'الحلويات'), 'Blueberry Cake', 'تشٌز كٌك بلو بيري', 60000),
((SELECT id FROM categories WHERE name_ar = 'الحلويات'), 'Lotus Cake', 'تشٌز كٌك لوتس', 65000),
((SELECT id FROM categories WHERE name_ar = 'الحلويات'), 'Oreo Cake', 'تشٌز كٌك اوريو', 65000),
((SELECT id FROM categories WHERE name_ar = 'الحلويات'), 'Brownie', 'براونز تورنادو', 75000),
((SELECT id FROM categories WHERE name_ar = 'الحلويات'), 'Basmati', 'باسمر دو', 50000),
((SELECT id FROM categories WHERE name_ar = 'الحلويات'), 'Asia Special', 'اسيا بول دايت', 60000);

UPDATE categories SET item_count = (SELECT COUNT(*) FROM category_items WHERE category_items.category_id = categories.id);
